mapserver:
  image: camptocamp/mapserver:${DOCKER_TAG}
  environment:
    MS_DEBUGLEVEL: 5
    MAPSERVER_CATCH_SEGV: 1
  links:
    - db
  ports:
    - 8380:8080
  volumes_from:
    - acceptance_config
  user: www-data

db:
  image: camptocamp/postgres:9.6
  environment:
    POSTGRES_USER: www-data
    POSTGRES_PASSWORD: www-data
    POSTGRES_DB: test
  volumes_from:
    - acceptance_config

acceptance_config:
  image: camptocamp/mapserver_acceptance_config:${DOCKER_TAG}

